# Generated by Django 5.2.10 on 2026-02-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
