# Generated by Django 5.2.10 on 2026-02-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_site', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
