# Generated by Django 5.2.10 on 2026-02-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_site', '0003_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default=1, upload_to='course_image/'),
            preserve_default=False,
        ),
    ]
