# Generated by Django 5.2.10 on 2026-02-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_site', '0005_cart_cartitem_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='curs_site.examquestion'),
            preserve_default=False,
        ),
    ]
