# Generated by Django 5.2.10 on 2026-02-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_site', '0006_examanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
