# Generated by Django 5.2.10 on 2026-02-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_site', '0009_alter_lesson_title_alter_lesson_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name_ky',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name_ru',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
